apiVersion: v1
kind: Service
metadata:
  name: hello-app
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: hello-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
