name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.29.0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.0

      - name: Authenticate to EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name hello-eks

      - name: Install Vault if not present
        run: |
          helm repo add hashicorp https://helm.releases.hashicorp.com
          helm upgrade --install vault hashicorp/vault --set "server.dev.enabled=true,injector.enabled=true"

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPO }}:latest .
          aws ecr get-login-password | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO }}
          docker push ${{ secrets.ECR_REPO }}:latest

      - name: Deploy app with Helm
        run: |
          helm upgrade --install hello-app ./helm-chart --set image.repository=${{ secrets.ECR_REPO }}             --set image.tag=latest
